apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: web-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: web-config
  - path: api-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: api-config
  - path: worker-patch.yaml
    target:
      kind: Deployment
      name: worker

images:
  - name: ghcr.io/vyacheslavkozyrev/testurio-web
    newTag: latest
  - name: ghcr.io/vyacheslavkozyrev/testurio-api
    newTag: latest
  - name: ghcr.io/vyacheslavkozyrev/testurio-worker
    newTag: latest
