apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: testurio
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
