apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: testurio
data:
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Cosmos__Endpoint: "<REPLACE>"
  ServiceBus__Namespace: "<REPLACE>"
  AzureAdB2C__Domain: "<REPLACE>"
  AzureAdB2C__ClientId: "<REPLACE>"
  AzureAdB2C__TenantId: "<REPLACE>"
