apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: testurio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          image: ghcr.io/vyacheslavkozyrev/testurio-worker:$(IMAGE_TAG)
          envFrom:
            - configMapRef:
                name: worker-config
            - secretRef:
                name: worker-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
