using System.Text.Json.Serialization;

namespace Testurio.Core.Models;

/// <summary>
/// A single API test scenario produced by <c>ApiTestGeneratorAgent</c> (stage 4).
/// Consumed by <c>HttpExecutor</c> (stage 5 / feature 0029) to issue real HTTP requests
/// and validate responses against the typed assertions.
/// </summary>
public sealed record ApiTestScenario
{
    /// <summary>UUID v4 identifier — generated by the agent, not the executor.</summary>
    public required string Id { get; init; }

    /// <summary>Human-readable title describing what this scenario validates.</summary>
    public required string Title { get; init; }

    /// <summary>HTTP method for the request.</summary>
    public required string Method { get; init; }

    /// <summary>Path and query string only — no scheme or host. E.g. <c>/api/users?page=1</c>.</summary>
    public required string Path { get; init; }

    /// <summary>Optional HTTP headers to include in the request. Null means no custom headers.</summary>
    public Dictionary<string, string>? Headers { get; init; }

    /// <summary>Optional JSON request body. Null for requests without a body (GET, DELETE).</summary>
    public object? Body { get; init; }

    /// <summary>
    /// Non-empty list of assertions to validate against the HTTP response.
    /// Must contain at least one <see cref="StatusCodeAssertion"/>.
    /// </summary>
    public required IReadOnlyList<Assertion> Assertions { get; init; }
}

/// <summary>
/// Base type for all API test assertions.
/// Discriminated via <see cref="Type"/> — concrete subtypes are
/// <see cref="StatusCodeAssertion"/>, <see cref="JsonPathAssertion"/>, and <see cref="HeaderAssertion"/>.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(StatusCodeAssertion), "status_code")]
[JsonDerivedType(typeof(JsonPathAssertion), "json_path")]
[JsonDerivedType(typeof(HeaderAssertion), "header")]
public abstract record Assertion
{
    /// <summary>Discriminator value — matches the <c>type</c> JSON property.</summary>
    public abstract string Type { get; }
}

/// <summary>
/// Asserts that the HTTP response status code equals <see cref="Expected"/>.
/// Every scenario must contain at least one assertion of this type.
/// </summary>
public sealed record StatusCodeAssertion : Assertion
{
    /// <inheritdoc />
    public override string Type => "status_code";

    /// <summary>Expected HTTP status code, e.g. 200, 201, 404.</summary>
    public required int Expected { get; init; }
}

/// <summary>
/// Asserts that a JSONPath expression evaluated against the response body
/// matches the <see cref="Expected"/> value.
/// Use <c>"*"</c> for <see cref="Expected"/> to check existence only (any non-null value is accepted).
/// </summary>
public sealed record JsonPathAssertion : Assertion
{
    /// <inheritdoc />
    public override string Type => "json_path";

    /// <summary>JSONPath expression, e.g. <c>$.data.id</c> or <c>$.items[0].name</c>.</summary>
    public required string Path { get; init; }

    /// <summary>
    /// Expected value as a string, or <c>"*"</c> for existence-only check.
    /// The executor coerces response values to string before comparison.
    /// </summary>
    public required string Expected { get; init; }
}

/// <summary>
/// Asserts that the specified response header is present and equals <see cref="Expected"/>.
/// </summary>
public sealed record HeaderAssertion : Assertion
{
    /// <inheritdoc />
    public override string Type => "header";

    /// <summary>Header name, e.g. <c>Content-Type</c>.</summary>
    public required string Name { get; init; }

    /// <summary>Expected header value.</summary>
    public required string Expected { get; init; }
}
