using System.Text.Json.Serialization;

namespace Testurio.Core.Models;

/// <summary>
/// A single UI end-to-end test scenario produced by <c>UiE2eTestGeneratorAgent</c> (stage 4).
/// Consumed by <c>PlaywrightExecutor</c> (stage 5 / feature 0029) to drive a real browser
/// through the described user flow.
/// </summary>
public sealed record UiE2eTestScenario
{
    /// <summary>UUID v4 identifier — generated by the agent, not the executor.</summary>
    public required string Id { get; init; }

    /// <summary>Human-readable title describing the user flow this scenario validates.</summary>
    public required string Title { get; init; }

    /// <summary>
    /// Ordered sequence of browser automation steps.
    /// Non-empty; must end with at least one assertion step
    /// (<see cref="AssertVisibleStep"/>, <see cref="AssertTextStep"/>, or <see cref="AssertUrlStep"/>).
    /// </summary>
    public required IReadOnlyList<UiStep> Steps { get; init; }
}

/// <summary>
/// Base type for all UI end-to-end test steps.
/// Discriminated via <see cref="Action"/> — concrete subtypes correspond to Playwright operations.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "action")]
[JsonDerivedType(typeof(NavigateStep), "navigate")]
[JsonDerivedType(typeof(ClickStep), "click")]
[JsonDerivedType(typeof(FillStep), "fill")]
[JsonDerivedType(typeof(AssertVisibleStep), "assert_visible")]
[JsonDerivedType(typeof(AssertTextStep), "assert_text")]
[JsonDerivedType(typeof(AssertUrlStep), "assert_url")]
public abstract record UiStep
{
    /// <summary>Discriminator value — matches the <c>action</c> JSON property.</summary>
    public abstract string Action { get; }
}

/// <summary>
/// Navigates the browser to the specified URL.
/// Typically the first step in every scenario.
/// </summary>
public sealed record NavigateStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "navigate";

    /// <summary>Full URL to navigate to, e.g. <c>https://staging.example.com/login</c>.</summary>
    public required string Url { get; init; }
}

/// <summary>
/// Clicks on the element matching <see cref="Selector"/>.
/// </summary>
public sealed record ClickStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "click";

    /// <summary>
    /// Playwright locator expression. Preference order:
    /// (1) role/text/label locators, e.g. <c>role=button[name="Submit"]</c>;
    /// (2) data-testid attributes, e.g. <c>[data-testid="submit-btn"]</c>;
    /// (3) CSS selectors as last resort.
    /// </summary>
    public required string Selector { get; init; }
}

/// <summary>
/// Fills the input element matching <see cref="Selector"/> with <see cref="Value"/>.
/// </summary>
public sealed record FillStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "fill";

    /// <summary>Playwright locator expression (see <see cref="ClickStep.Selector"/> for priority order).</summary>
    public required string Selector { get; init; }

    /// <summary>Text value to type into the input.</summary>
    public required string Value { get; init; }
}

/// <summary>
/// Asserts that the element matching <see cref="Selector"/> is visible in the viewport.
/// </summary>
public sealed record AssertVisibleStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "assert_visible";

    /// <summary>Playwright locator expression (see <see cref="ClickStep.Selector"/> for priority order).</summary>
    public required string Selector { get; init; }
}

/// <summary>
/// Asserts that the element matching <see cref="Selector"/> contains the text <see cref="Expected"/>.
/// </summary>
public sealed record AssertTextStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "assert_text";

    /// <summary>Playwright locator expression (see <see cref="ClickStep.Selector"/> for priority order).</summary>
    public required string Selector { get; init; }

    /// <summary>Expected text content of the element.</summary>
    public required string Expected { get; init; }
}

/// <summary>
/// Asserts that the browser's current URL matches <see cref="Expected"/> (exact or prefix match).
/// </summary>
public sealed record AssertUrlStep : UiStep
{
    /// <inheritdoc />
    public override string Action => "assert_url";

    /// <summary>
    /// Expected URL pattern. The executor accepts an exact match or prefix match.
    /// E.g. <c>https://staging.example.com/dashboard</c> or <c>/dashboard</c>.
    /// </summary>
    public required string Expected { get; init; }
}
